apiVersion: v1
kind: Service
metadata:
  labels:
    app: stable-diffusion
  name: stable-diffusion-svc
  namespace: gpu-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7860
  selector:
    app: stable-diffusion
  type: LoadBalancer