---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stable-diffusion-cm
  namespace: gpu-demo
data:
  CLI_FLAGS: "--extra-models-cpu --optimized-turbo"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stable-diffusion-sa
  namespace: gpu-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion
  namespace: gpu-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion
  template:
    metadata:
      labels:
        app: stable-diffusion
    spec:
      serviceAccountName: stable-diffusion-sa
      containers:
      - envFrom:
        - configMapRef:
            name: stable-diffusion-cm
        image: amithkk/stable-diffusion:latest
        name: stable-diffusion
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
        ports:
        - containerPort: 7860
        volumeMounts:
        - mountPath: /models
          name: stable-diffusion-store
      dnsPolicy: ClusterFirst
      initContainers:
      - image: alpine
        name: initialize-stable-models
        command: ["/bin/sh", "-c"]
        args:
        - "apk add --no-cache wget && wget -nc https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt -O /models/model.ckpt; wget -nc https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.3.pth -O /models/GFPGANv1.3.pth; wget -nc https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth -O /models/RealESRGAN_x4plus.pth; wget -nc https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth -O /models/RealESRGAN_x4plus_anime_6B.pth;"
        volumeMounts:
        - mountPath: /models
          name: stable-diffusion-store
      nodeSelector:
        eks-node: gpu
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: stable-diffusion-store
        persistentVolumeClaim:
          claimName: stable-diffusion-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-pvc
  namespace: gpu-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: gp3